// Generator Functions


// Function that returns a random index (number) of a string value tht is passed in as an argurment 
function randomIndex(str){
    return Math.floor(Math.random() * str.length);
}
console.log(randomIndex(`example`));

// example:
//randomIndex(`abc`);
    //  (Math.random() * str.length); 
        // Will return random number within index length [0 - 1.99]
    //  Math.floor([random]);
        // Will drop decimal and round off number to its nearest interget in downward direction (randomIndex 0, 1 )



// Function that returns a random letter using a random index in the "letter" string variable
function randomLetter(){
    const letters = "abcdefghijklmnopqrstuvwxyz";
    letters[randomIndex(letters)];  
    //randomIndex(letters);
        // passing in letters length (26) as string value in the randomIndex function code
    // letters[randomIndex(letters)]; 
        // will return corresponding letter of random index generated by randomIndex function
}
    console.log(randomLetter());



function getRandomUpper(){
    const letter = randomLetter();
        //Running the "randomLetter" function to create a random (lowercase) letter and setting that value to the letter variable
    return letter.toUpperCase();
        // converting the returned (lowercase) letter (from randomLetter() function)  .toUpperCase Letter and returning it from the function
}   
    console.log(getRandomUpper());



function getRandomLower() {
    return randomLetter();
}
    console.log(getRandomLower());



function getRandomNumber(){
    const numbers = `1234567890`;
    return numbers[randomIndex(numbers)];
        // will return a randomIndex from 1-9 using a random index in the "numbers" string
}
    console.log(getRandomNumber());



function getRandomSymbol(){
    const symbols = `'!@#$%^&*(){}[]=<>/,.'`
    return symbols[randomIndex(symbols)];
        // REturrning a random symbol using a random index in the "symbols" string
}
    console.log(getRandomSymbol());
